### ISSUE TITLE
Incompatibility with Corpse

### ISSUE THREAD

**Issue by SlimF** [Vatuu/qui2ver#2]
If you die while carrying the quiver in its slot with the [Corpse](https://www.curseforge.com/minecraft/mc-mods/corpse) mod installed, both the quiver and the arrows disappear instead of staying in the corpse.

**Comment by ArMoReDfUrY** [comment]
corpse works fine for me, i get both quiver and arrows on my corpse.
this mod seems to have some odd conflicts, i have been testing it for 2 hours now and i still have not found the culprit yet

**Comment by SlimF** [comment]
Maybe it's a mix with one of the other mods I have installed? I'll look around more and report if I find something

**Comment by ArMoReDfUrY** [comment]
i have a small list of what i have tested already in my bug report, should help narrow it down a bit.
will do the same if i find something too.

**Comment by SlimF** [comment]
I tried removing everything other than Corpse, Qui2ver and Mixins. Both quiver and arrows still disappear if they are equipped. [Here's](https://pastebin.com/qVG6hYgn) my log in case it can help

**Comment by Vatuu** [comment]
I can't really conclude anything from that log.

**Comment by ArMoReDfUrY** [comment]
> I tried removing everything other than Corpse, Qui2ver and Mixins. Both quiver and arrows still disappear if they are equipped. [Here's](https://pastebin.com/qVG6hYgn) my log in case it can help

you should use the debug log, more info.

**Comment by SlimF** [comment]
> 
> 
> > I tried removing everything other than Corpse, Qui2ver and Mixins. Both quiver and arrows still disappear if they are equipped. [Here's](https://pastebin.com/qVG6hYgn) my log in case it can help
> 
> you should use the debug log, more info.

Oops, my bad! [Here](https://pastebin.com/NReBFuGA)'s debug.log

**Comment by ArMoReDfUrY** [comment]
are you running the /kill command in creative mode or are you switching back to survival 1st?

**Comment by SlimF** [comment]
I tried in both creative and survival

**Comment by ArMoReDfUrY** [comment]
all i can say is that's really odd... the exact same setup for my testing environment and it works without issue.....
real head scratcher that.

**Comment by Vatuu** [comment]
Well, I wonder if I should keep this open if we can't even reproduce the glitch... I've attempted it myself, and I don't encounter it as well. I'll close this issue for now, until someone else encounters this problem so we can narrow down the cause.
