### ISSUE TITLE
Unable to fire arrows from quiver

### ISSUE THREAD

**Issue by ArMoReDfUrY** [Vatuu/qui2ver#3]
-Forge 31.1.63
-qui2ver 1.2

-Single player world. 

slot holds quiver and arrow slot holds arrows but unable to fire any at all unless they are in the hot bar, inventory or off hand.

i also have curios and cosmetic armour mods installed i thought they might be conflicting but no they work fine together.
been testing for over 2 hours now and no luck finding the conflict yet... 
my pack has around 130 mods but those are the only 2 that add player slots.
will run more tests later in the day to try narrow it down.

so far all these mods work fine together

**backpacked-1.4.1-1.15.2
caelus-FORGE-1.15.2-2.0-beta2
corpse-1.15.2-1.0.4
CosmeticArmorReworked-1.15.2-v2
curios-FORGE-1.15.2-2.0.2.2
curiouselytra-FORGE-1.15.2-2.0
curiousshulkerboxes-FORGE-1.15.2-2.0.0.1
jei-1.15.2-6.0.0.4
OptiForge-MC1.15.2-0.1.14
preview_OptiFine_1.15.2_HD_U_G1_pre13**

118 left to go... fun times.

**Comment by Vatuu** [comment]
I can't really tell you which one might conflict, but if it does there is some serious overwriting issues going on. The quiver uses mixins, which injects my own code into Minecraft's ammunitions selection system. So the only way that this could break is, if some mod overwrites that system completely.
Maybe that will help to find the culprit.

**Comment by ArMoReDfUrY** [comment]
ok after some very extensive testing i have found it!

[https://www.curseforge.com/minecraft/mc-mods/cofh-core](cofh-core)

this has been tested with just cofh core, mixin bootstrap and quiver.
i have also tested it with every mod i have at once **minus** cofh core and it works perfectly fine.

i hope we can find a fix for this cause i need cofh core for the ensorcellation mod as it's the only 1.15.x mod with the Soulbound enchantment i'm aware of. 
[https://www.curseforge.com/minecraft/mc-mods/ensorcellation](url)

i will try to report it to the cofh team too but that may be tricky as they don't seem to have an issue tracker on their github page.

**Comment by ArMoReDfUrY** [comment]
i spoke to the CoFH dev and he said that it's something that they most probably can't fix on their end due to the way the slots work.

**Comment by Vatuu** [comment]
Can you show me what they said?

**Comment by ArMoReDfUrY** [comment]
i quote
**King LemmingToday at 7:22 PM**
Unfortunately there's no way for us to "know" about an additional slot so we can't possibly check for it
I'm not sure there can be a fix for that

**Comment by Vatuu** [comment]
The quiver is not operating from a slot basis, it's injecting its own conditions into the ammo function. Are they overwriting that completely?

**Comment by ArMoReDfUrY** [comment]
i'll pop on the discord again and ask. might be a bit for a reply.

**Comment by ArMoReDfUrY** [comment]
no reply yet but i have been digging through their source code a bit and it looks like they implement a few things for the bow and a bunch of arrow related stuff for their Archer's Paradox mod.
[https://www.curseforge.com/minecraft/mc-mods/archers-paradox](url)
bow has some on draw events for an infinity fix enchantment and another called quickdraw.
and i found some capability files that are probably the issue.
here is a link to the source if you want to take a look, look in the events and capability files.
[https://github.com/KingLemming/1.15/tree/master/CoFHCore/src/main/java/cofh/lib](url)
 EDIT: yeh confirmed the ammo function replacement.
King LemmingToday at 3:07 AM
I'm using event handling to skip the normal functionality yes. We do this for our own quiver support, the item based kind.

**Comment by ArMoReDfUrY** [comment]
i'd say you can mark CoFH core as incompatable and close this if you like

**Comment by Vatuu** [comment]
Sounds good, maybe I can figure something out after all.
